baseURL = 'https://liemly.me'
languageCode = 'en-us'
title = 'Liem Ly'
theme = 'hugo-coder'
author = 'Liem Ly'
info = 'Technologist'
googleAnalytics = 'G-1R1T2DMPBB'

[params]
  author = "Liem Ly"
  colorScheme = "auto"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 2
  url = "https://github.com/liemlyquan"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/liemlyquan/"
[[params.social]]
  name = "Email"
  icon = "fa fa-inbox fa-2x"
  weight = 2
  url = "mailto:liemlyquan@gmail.com"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"

